/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author u07862281136
 */
public class JDlgLab_Produtos extends java.awt.Dialog {

    /**
     * Creates new form JDlgLab_Produtos
     */
    public JDlgLab_Produtos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         setTitle("Produtos");
        setLocationRelativeTo(null);
        habilitar(false);
    }
    
     public void habilitar(boolean valor) {
        jTxtLab_Codigo.setEnabled(valor);
        jTxtLab_descricao.setEnabled(valor);
        jTxtLab_nomeProduto.setEnabled(valor);
        jTxtLab_preco.setEnabled(valor);
        jCboLab_tamanho.setEnabled(valor);
        jChbLab_Ativo.setEnabled(valor);
        jBtnLab_Confirmar.setEnabled(valor);
        jBtnLab_Cancelar.setEnabled(valor);
        jBtnLab_Incluir.setEnabled(!valor);
        jBtnLab_Alterar.setEnabled(!valor);
        jBtnLab_Excluir.setEnabled(!valor);
        jBtnLab_Pesq.setEnabled(!valor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtLab_Codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtLab_nomeProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtLab_descricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCboLab_tamanho = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTxtLab_preco = new javax.swing.JTextField();
        jChbLab_Ativo = new javax.swing.JCheckBox();
        jBtnLab_Incluir = new javax.swing.JButton();
        jBtnLab_Alterar = new javax.swing.JButton();
        jBtnLab_Excluir = new javax.swing.JButton();
        jBtnLab_Confirmar = new javax.swing.JButton();
        jBtnLab_Cancelar = new javax.swing.JButton();
        jBtnLab_Pesq = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel2.setText("Nome do Produto");

        jLabel3.setText("Descrição");

        jLabel4.setText("Tamanho");

        jCboLab_tamanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Preço");

        jChbLab_Ativo.setText("Ativo");

        jBtnLab_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-adicionar.png"))); // NOI18N
        jBtnLab_Incluir.setText("Incluir");
        jBtnLab_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLab_IncluirActionPerformed(evt);
            }
        });

        jBtnLab_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnLab_Alterar.setText("Alterar");
        jBtnLab_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLab_AlterarActionPerformed(evt);
            }
        });

        jBtnLab_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir2.png"))); // NOI18N
        jBtnLab_Excluir.setText("Excluir");
        jBtnLab_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLab_ExcluirActionPerformed(evt);
            }
        });

        jBtnLab_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/aprovado.png"))); // NOI18N
        jBtnLab_Confirmar.setText("Confirmar");
        jBtnLab_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLab_ConfirmarActionPerformed(evt);
            }
        });

        jBtnLab_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/recarregar.png"))); // NOI18N
        jBtnLab_Cancelar.setText("Cancelar");
        jBtnLab_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLab_CancelarActionPerformed(evt);
            }
        });

        jBtnLab_Pesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa.png"))); // NOI18N
        jBtnLab_Pesq.setText("Pesquisar");
        jBtnLab_Pesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLab_PesqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtLab_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtLab_descricao)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtLab_preco)
                                    .addComponent(jTxtLab_nomeProduto)
                                    .addComponent(jCboLab_tamanho, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jChbLab_Ativo)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnLab_Incluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnLab_Alterar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnLab_Excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnLab_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnLab_Cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnLab_Pesq)
                        .addGap(0, 79, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtLab_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtLab_nomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTxtLab_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jCboLab_tamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTxtLab_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jChbLab_Ativo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnLab_Incluir)
                    .addComponent(jBtnLab_Alterar)
                    .addComponent(jBtnLab_Excluir)
                    .addComponent(jBtnLab_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnLab_Cancelar)
                    .addComponent(jBtnLab_Pesq))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jBtnLab_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLab_IncluirActionPerformed
        // TODO add your handling code here:
        habilitar(true);
    }//GEN-LAST:event_jBtnLab_IncluirActionPerformed

    private void jBtnLab_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLab_AlterarActionPerformed
        // TODO add your handling code here:
        habilitar(true);
    }//GEN-LAST:event_jBtnLab_AlterarActionPerformed

    private void jBtnLab_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLab_ExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "A exclusão não poderá ser desfeita. Deseja continuar?",
            "Excluir registro", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jBtnLab_ExcluirActionPerformed

    private void jBtnLab_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLab_ConfirmarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_jBtnLab_ConfirmarActionPerformed

    private void jBtnLab_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLab_CancelarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_jBtnLab_CancelarActionPerformed

    private void jBtnLab_PesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLab_PesqActionPerformed
        // TODO add your handling code here:
        JOptionPane.showInputDialog(null, "Informe o código do produto:");
    }//GEN-LAST:event_jBtnLab_PesqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgLab_Produtos dialog = new JDlgLab_Produtos(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLab_Alterar;
    private javax.swing.JButton jBtnLab_Cancelar;
    private javax.swing.JButton jBtnLab_Confirmar;
    private javax.swing.JButton jBtnLab_Excluir;
    private javax.swing.JButton jBtnLab_Incluir;
    private javax.swing.JButton jBtnLab_Pesq;
    private javax.swing.JComboBox<String> jCboLab_tamanho;
    private javax.swing.JCheckBox jChbLab_Ativo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTxtLab_Codigo;
    private javax.swing.JTextField jTxtLab_descricao;
    private javax.swing.JTextField jTxtLab_nomeProduto;
    private javax.swing.JTextField jTxtLab_preco;
    // End of variables declaration//GEN-END:variables
}
