/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author u07862281136
 */
public class JDlgLab_Vendedores extends java.awt.Dialog {

    /**
     * Creates new form JDlgLab_Vendedores
     */
    public JDlgLab_Vendedores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         setTitle("Vendedores");
        setLocationRelativeTo(null);
        habilitar(false);
    }
    
     public void habilitar(boolean valor) {
        jTxtLab_codigo.setEnabled(valor);
        jTxtLab_Nome.setEnabled(valor);
        jTxtLab_celular.setEnabled(valor);
        jTxtLab_dataCadastro.setEnabled(valor);
        jTxtLab_email.setEnabled(valor);
        jTxtLab_metaVendas.setEnabled(valor);
        jTxtLab_nomeSistema.setEnabled(valor);
        jPwfLab_senhaSistema.setEnabled(valor);
        jBtnLab_Confirmar.setEnabled(valor);
        jBtnLab_Cancelar.setEnabled(valor);
        jBtnLab_Incluir.setEnabled(!valor);
        jBtnLab_Alterar.setEnabled(!valor);
        jBtnLab_Excluir.setEnabled(!valor);
        jBtnLab_Pesq.setEnabled(!valor);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtLab_codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxtLab_Nome = new javax.swing.JTextField();
        jTxtLab_celular = new javax.swing.JTextField();
        jTxtLab_email = new javax.swing.JTextField();
        jTxtLab_metaVendas = new javax.swing.JTextField();
        jTxtLab_dataCadastro = new javax.swing.JTextField();
        jTxtLab_nomeSistema = new javax.swing.JTextField();
        jPwfLab_senhaSistema = new javax.swing.JPasswordField();
        jBtnLab_Incluir = new javax.swing.JButton();
        jBtnLab_Alterar = new javax.swing.JButton();
        jBtnLab_Excluir = new javax.swing.JButton();
        jBtnLab_Confirmar = new javax.swing.JButton();
        jBtnLab_Cancelar = new javax.swing.JButton();
        jBtnLab_Pesq = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel2.setText("Nome");

        jLabel3.setText("Celular");

        jLabel4.setText("E-mail");

        jLabel5.setText("Usuário");

        jLabel6.setText("Meta de Vendas");

        jLabel7.setText("Senha");

        jLabel8.setText("Data de Cadastro");

        jBtnLab_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-adicionar.png"))); // NOI18N
        jBtnLab_Incluir.setText("Incluir");
        jBtnLab_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLab_IncluirActionPerformed(evt);
            }
        });

        jBtnLab_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnLab_Alterar.setText("Alterar");
        jBtnLab_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLab_AlterarActionPerformed(evt);
            }
        });

        jBtnLab_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir2.png"))); // NOI18N
        jBtnLab_Excluir.setText("Excluir");
        jBtnLab_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLab_ExcluirActionPerformed(evt);
            }
        });

        jBtnLab_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/aprovado.png"))); // NOI18N
        jBtnLab_Confirmar.setText("Confirmar");
        jBtnLab_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLab_ConfirmarActionPerformed(evt);
            }
        });

        jBtnLab_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/recarregar.png"))); // NOI18N
        jBtnLab_Cancelar.setText("Cancelar");
        jBtnLab_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLab_CancelarActionPerformed(evt);
            }
        });

        jBtnLab_Pesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa.png"))); // NOI18N
        jBtnLab_Pesq.setText("Pesquisar");
        jBtnLab_Pesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLab_PesqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtLab_Nome)
                                    .addComponent(jTxtLab_codigo)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtLab_celular, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtLab_email, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxtLab_metaVendas)
                            .addComponent(jTxtLab_dataCadastro)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtLab_nomeSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(28, 28, 28)
                                .addComponent(jPwfLab_senhaSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnLab_Incluir)
                .addGap(18, 18, 18)
                .addComponent(jBtnLab_Alterar)
                .addGap(18, 18, 18)
                .addComponent(jBtnLab_Excluir)
                .addGap(18, 18, 18)
                .addComponent(jBtnLab_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnLab_Cancelar)
                .addGap(18, 18, 18)
                .addComponent(jBtnLab_Pesq)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtLab_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jTxtLab_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtLab_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtLab_metaVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtLab_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtLab_dataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtLab_nomeSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPwfLab_senhaSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnLab_Incluir)
                    .addComponent(jBtnLab_Alterar)
                    .addComponent(jBtnLab_Excluir)
                    .addComponent(jBtnLab_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnLab_Cancelar)
                    .addComponent(jBtnLab_Pesq))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jBtnLab_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLab_IncluirActionPerformed
        // TODO add your handling code here:
        habilitar(true);
    }//GEN-LAST:event_jBtnLab_IncluirActionPerformed

    private void jBtnLab_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLab_AlterarActionPerformed
        // TODO add your handling code here:
        habilitar(true);
    }//GEN-LAST:event_jBtnLab_AlterarActionPerformed

    private void jBtnLab_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLab_ExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "A exclusão não poderá ser desfeita. Deseja continuar?",
            "Excluir registro", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jBtnLab_ExcluirActionPerformed

    private void jBtnLab_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLab_ConfirmarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_jBtnLab_ConfirmarActionPerformed

    private void jBtnLab_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLab_CancelarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_jBtnLab_CancelarActionPerformed

    private void jBtnLab_PesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLab_PesqActionPerformed
        // TODO add your handling code here:
        JOptionPane.showInputDialog(null, "Informe o código do vendedor:");
    }//GEN-LAST:event_jBtnLab_PesqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgLab_Vendedores dialog = new JDlgLab_Vendedores(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLab_Alterar;
    private javax.swing.JButton jBtnLab_Cancelar;
    private javax.swing.JButton jBtnLab_Confirmar;
    private javax.swing.JButton jBtnLab_Excluir;
    private javax.swing.JButton jBtnLab_Incluir;
    private javax.swing.JButton jBtnLab_Pesq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPwfLab_senhaSistema;
    private javax.swing.JTextField jTxtLab_Nome;
    private javax.swing.JTextField jTxtLab_celular;
    private javax.swing.JTextField jTxtLab_codigo;
    private javax.swing.JTextField jTxtLab_dataCadastro;
    private javax.swing.JTextField jTxtLab_email;
    private javax.swing.JTextField jTxtLab_metaVendas;
    private javax.swing.JTextField jTxtLab_nomeSistema;
    // End of variables declaration//GEN-END:variables
}
