/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author u07862281136
 */
public class JFrmLab_Principal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmLab_Principal() {
         initComponents();
         setTitle("Sistema do IFMS");
         setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuLab_Cadastros = new javax.swing.JMenu();
        jMnuLab_Usuarios = new javax.swing.JMenuItem();
        jMnuLab_Clientes = new javax.swing.JMenuItem();
        jMnuLab_Fornecedor = new javax.swing.JMenuItem();
        jMnuLab_Produtos = new javax.swing.JMenuItem();
        jMnuLab_Vendedores = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuLab_Sair = new javax.swing.JMenuItem();
        jMnuLab_Movimento = new javax.swing.JMenu();
        jMnuLab_Compras = new javax.swing.JMenuItem();
        jMnuLab_Vendas = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMnuLab_Cadastros.setText("Cadastro");

        jMnuLab_Usuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuLab_Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jMnuLab_Usuarios.setText("Usuários");
        jMnuLab_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuLab_UsuariosActionPerformed(evt);
            }
        });
        jMnuLab_Cadastros.add(jMnuLab_Usuarios);

        jMnuLab_Clientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuLab_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jMnuLab_Clientes.setText("Clientes");
        jMnuLab_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuLab_ClientesActionPerformed(evt);
            }
        });
        jMnuLab_Cadastros.add(jMnuLab_Clientes);

        jMnuLab_Fornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuLab_Fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedor.png"))); // NOI18N
        jMnuLab_Fornecedor.setText("Fornecedor");
        jMnuLab_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuLab_FornecedorActionPerformed(evt);
            }
        });
        jMnuLab_Cadastros.add(jMnuLab_Fornecedor);

        jMnuLab_Produtos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuLab_Produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        jMnuLab_Produtos.setText("Produtos");
        jMnuLab_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuLab_ProdutosActionPerformed(evt);
            }
        });
        jMnuLab_Cadastros.add(jMnuLab_Produtos);

        jMnuLab_Vendedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuLab_Vendedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendedor.png"))); // NOI18N
        jMnuLab_Vendedores.setText("Vendedores");
        jMnuLab_Vendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuLab_VendedoresActionPerformed(evt);
            }
        });
        jMnuLab_Cadastros.add(jMnuLab_Vendedores);
        jMnuLab_Cadastros.add(jSeparator1);

        jMnuLab_Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuLab_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jMnuLab_Sair.setText("Sair");
        jMnuLab_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuLab_SairActionPerformed(evt);
            }
        });
        jMnuLab_Cadastros.add(jMnuLab_Sair);

        jMenuBar1.add(jMnuLab_Cadastros);

        jMnuLab_Movimento.setText("Movimento");

        jMnuLab_Compras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuLab_Compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/compras.png"))); // NOI18N
        jMnuLab_Compras.setText("Compras");
        jMnuLab_Movimento.add(jMnuLab_Compras);

        jMnuLab_Vendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuLab_Vendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas.png"))); // NOI18N
        jMnuLab_Vendas.setText("Vendas");
        jMnuLab_Movimento.add(jMnuLab_Vendas);

        jMenuBar1.add(jMnuLab_Movimento);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuLab_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuLab_SairActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jMnuLab_SairActionPerformed

    private void jMnuLab_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuLab_UsuariosActionPerformed
        // TODO add your handling code here:
       JDlgLab_Usuarios jDlgLab_Usuarios = new JDlgLab_Usuarios(null, true);
       jDlgLab_Usuarios.setVisible(true);
    }//GEN-LAST:event_jMnuLab_UsuariosActionPerformed

    private void jMnuLab_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuLab_ClientesActionPerformed
        // TODO add your handling code here:
          JDlgLab_Clientes jDlgLab_Clientes = new JDlgLab_Clientes(null, true);
       jDlgLab_Clientes.setVisible(true);
    }//GEN-LAST:event_jMnuLab_ClientesActionPerformed

    private void jMnuLab_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuLab_FornecedorActionPerformed
        // TODO add your handling code here:
         JDlgLab_Fornecedor jDlgLab_Fornecedor = new JDlgLab_Fornecedor(null, true);
       jDlgLab_Fornecedor.setVisible(true);
    }//GEN-LAST:event_jMnuLab_FornecedorActionPerformed

    private void jMnuLab_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuLab_ProdutosActionPerformed
        // TODO add your handling code here:
         JDlgLab_Produtos jDlgLab_Produtos = new JDlgLab_Produtos(null, true);
       jDlgLab_Produtos.setVisible(true);
    }//GEN-LAST:event_jMnuLab_ProdutosActionPerformed

    private void jMnuLab_VendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuLab_VendedoresActionPerformed
        // TODO add your handling code here:
        JDlgLab_Vendedores jDlgLab_Vendedores  = new JDlgLab_Vendedores (null, true);
       jDlgLab_Vendedores .setVisible(true);
    }//GEN-LAST:event_jMnuLab_VendedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmLab_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmLab_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmLab_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmLab_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmLab_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMnuLab_Cadastros;
    private javax.swing.JMenuItem jMnuLab_Clientes;
    private javax.swing.JMenuItem jMnuLab_Compras;
    private javax.swing.JMenuItem jMnuLab_Fornecedor;
    private javax.swing.JMenu jMnuLab_Movimento;
    private javax.swing.JMenuItem jMnuLab_Produtos;
    private javax.swing.JMenuItem jMnuLab_Sair;
    private javax.swing.JMenuItem jMnuLab_Usuarios;
    private javax.swing.JMenuItem jMnuLab_Vendas;
    private javax.swing.JMenuItem jMnuLab_Vendedores;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
